name: camera_app
description: A Camera App using CameraAwesome.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  better_open_file: ^3.6.4
  cross_file: ^0.3.3+6
  flutter:
    sdk: flutter
  camerawesome:
    path: ../
  path_provider: ^2.1.1
  flutter_svg:
  # google_mlkit_face_detection: ^0.9.0
  # google_mlkit_barcode_scanning: ^0.10.0
  # google_mlkit_text_recognition: ^0.11.0
  image: ^4.1.3
  meta: ^1.10.0
  # rxdart: ^0.27.7
  video_player: ^2.8.1
  share_plus: ^10.1.2
  uuid: ^4.5.1
  ffmpeg_kit_flutter_full_gpl: 6.0.3

  # vibration: ^2.0.1
  # flutter_media_metadata: ^1.0.0+1
  # permission_handler: ^11.3.1
  # image_gallery_saver: ^2.0.3

dev_dependencies:
  exif: ^3.3.0
  flutter_test:
    sdk: flutter
  patrol: ^1.1.0
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - images/a_dot_ham.jpeg

patrol:
  android:
    package_name: com.example.camera_app
  ios:
    bundle_id:
